name: QueueSystem
main: me.tulio.queue.QueueMain
version: 1.0-SNAPSHOT
author: TulioTriste
commands:
  leavequeue: 
    aliases: ["leave", "salir", "salircola"]
  pausequeue: 
    aliases: ["pause", "pausarcola", "detenercola"]
  playqueue: 
    aliases: ["play"]
  setlimit:
    aliases: ["limit", "limitar"]